

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { trpc } from "@/utils/trpc";
import TRPC_Provider from "@/Components/TRPC_Provider";
import Footer from "@/Components/Home/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="overflow-x-hidden bg-white" >
        <TRPC_Provider>{children}</TRPC_Provider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
